import firebase from "../../context/firebaseContext"
import "firebase/auth";
import "firebase/firestore";

let fs = firebase.firestore()

const CLASS_ADMIN = "classAdmins"
const USER_CLASS_ADMIN = "userClassAdmins"
const ADMINS = "admins"
const NOTIFICATIONS = "adminNotifications"
const USER_NOTIFICATIONS = "userAdminNotifications"
const INVITES = "invites"
const CLASSES = "classes"
const USERS = "users"


export default function mTea(){}



export function sendAdminInvite(uid, boxID, gymClassID, owner, boxTitle, username){

    let inviteRef = fs.collection(NOTIFICATIONS).doc(boxID)
    .collection(CLASSES).doc(gymClassID)
    .collection(NOTIFICATIONS)


    let data = {
        uid: uid,
        owner: owner,
        boxID: boxID,
        boxTitle: boxTitle,
        username: username
    }


    return new Promise((res, rej) => {
        console.log("idAdmin?")
        isClassAdmin(uid, boxID, gymClassID).then(isAdmin => {
            if(!isAdmin){
                console.log("isSent?")
                isNotificationSent(uid, boxID, gymClassID)
                .then(isSent => {
                    if(isSent){
                        res("Admin notified already.")
                    }else{

                        console.log("Setting adminf notify data")
                        let doc = inviteRef.doc(uid)

                        doc.set(data)
                        .then(() => { res("Sent admin invite.") })
                        .catch(err => { rej(err) })
                    }
                })
                .catch(err => {
                    rej(err)
                })
            }else{
                res("Already an admin.")
            }
        })

    })
}

function isNotificationSent(uid, boxID, gymClassID){
    /* Checks if notifications has been sent to the user for a class invite.

    Queries "notifications/admins/invites/" for uid and gymClassID.
    Returns true if found, otherwise false

    Args:
        uid A string autogenerated for the user.
        gymClassID A string autogenerated for the document.
     */
    return new Promise((res, rej) => {
        console.log("isSent: start")
        fs.collection(NOTIFICATIONS).doc(boxID)
        .collection(CLASSES).doc(gymClassID)
        .collection(NOTIFICATIONS).doc(uid)
        .get().then(ss => {
            console.log("isSent: snapshot")
            if(ss.empty){
                res(false)
            }else{
                res(true)
            }
        },
        err => { rej(err) })
    })
}

export function getUserAdminInvites(uid){
    // go through boxes and classes to find all invites.
    return  fs.collection(USER_NOTIFICATIONS).doc(uid)
    .collection("boxes")

}


export function removeNotification(notify){
    return new Promise((res, rej) => {
            res("No notifications found.")
    })
}



export function getClassAdmins(boxID, gymClassID){
    return fs.collection(CLASS_ADMIN).doc(boxID)
    .collection("classes").doc(gymClassID)
    .collection("admins")

}

export function getUserClassAdmins(uid){
    // Need to proccess
    return fs.collection(USER_CLASS_ADMIN).doc(uid)
    .collection("boxes")



}

export function isClassAdmin (uid, boxID, gymClassID){
    return new Promise((res, rej) => {
        fs.collection(CLASS_ADMIN).doc(boxID)
        .collection("classes").doc(gymClassID)
        .collection("admins").doc(uid)
        .get()
        .then(adminSS => {
            if(!adminSS.empty){
                res(true)
            }else{
                res(false)
            }
        })
        .catch(err => {
            rej(err)
        })
    })
}

export function setClassAdmin(uid, boxID, gymClassID, owner){
    return new Promise((res, rej) => {
        isClassAdmin(uid, gymClassID)
        .then(isMember => {
            if(!isMember){
                let data = {
                    uid: uid,
                    boxID: boxID,
                    gymClassID: gymClassID,
                    owner: owner
                }

                let doc = fs.collection(CLASS_ADMIN).doc(boxID)
                .collection(CLASS_ADMIN).doc(boxID)
                .collection("classes").doc(gymClassID)
                .collection("admins").doc(uid)

                let shallow = fs.collection(USER_CLASS_ADMIN).doc(uid)
                .collection("boxes").doc(boxID)
                .collection("classes").doc(gymClassID)
                .collection("admins").doc(uid)



                Promise.all([
                    doc.set({ ...data, classAdminID: doc.id }),
                    shallow.set({...data, classAdminID: doc.id})
                ])
                .then( () => {
                    res("Added user as an admin.")
                })





                .catch(err => { rej(err) })
            }else{
                res("User is an admin.")
            }
        })
        .catch(err => {
            rej(err)
        })
    })
}

export function removeAdmin(classAdmin){

    return Promise.all([
        fs.collection(CLASS_ADMIN)
        .doc(classAdmin.classAdminID)
        .delete(),

        fs.collection(USER_CLASS_ADMIN).doc(classAdmin.gymClassID)
        .collection("users").doc(classAdmin.uid)
        .delete()

    ])
}